#!/bin/bash
#
# Example post_extract script, committing any changes to a local bzr branch
#

die() {
  echo $*
  exit 1
}

DIR=$1 || exit 1
cd $DIR || exit 2

BZR=/usr/bin/bzr
test -x $BZR || die "Cannot find bzr executable"

# Init a local bzr branch (if required)
test -d .bzr || $BZR init . || die "bzr init failed"

# Commit any changes found
CHANGES=$($BZR status --short)
if [ -n "$CHANGES" ]; then
  NOW=$(date '+%Y-%m-%d %H:%M:%S')
  OUT=$($BZR add . 2>&1)
  if [ $? -gt 0 ]; then
    echo $OUT
  fi
  OUT=$($BZR commit --strict -m "Changes to $NOW" 2>&1)
  if [ $? -gt 0 ]; then
    echo $OUT
  fi
fi

