#!/bin/sh
#
# Example post_extract script, packing extracted files into a date-stamped tarball
#

ROOT=$1 || exit 1
HOST=$2 || exit 2
FILE=$3 || exit 3

DIR="$ROOT/$HOST"
cd $DIR || exit 99

DATE=`date +%Y%m%d`

# Create the tarball
tar -zcf $HOST-$DATE.tar.gz --exclude "$HOST*tar.gz" --remove-files *

# Tar won't remove directories, apparently - so do that explicitly
find . -xdev -depth -type d -regex '^\./.+' -exec rmdir {} \;

