#!/bin/bash
#
# Example post_extract script, committing any changes to a local bzr branch
#

die() {
  echo $*
  exit 99
}

ROOT=$1 || exit 1
HOST=$2 || exit 2
FILE=$3 || exit 3

DIR="$ROOT/$HOST"
cd $DIR || die "Cannot cd to '$DIR'"

BZR=/usr/bin/bzr
test -x $BZR || die "Cannot find bzr executable"

# Init a local bzr branch (if required)
test -d .bzr || $BZR init . || die "bzr init failed"

# Commit any changes found
CHANGES=$($BZR status --short)
if [ -n "$CHANGES" ]; then
  NOW=$(date '+%Y-%m-%d %H:%M:%S')
  OUT=$($BZR add . 2>&1)
  if [ $? -gt 0 ]; then
    echo $OUT
  fi
  OUT=$($BZR commit --strict -m "Changes to $NOW" 2>&1)
  if [ $? -gt 0 ]; then
    echo $OUT
  fi
else
  # Revert if no changes since we've probably have deleted stuff earlier
  OUT=$($BZR revert)
  if [ $? -gt 0 ]; then
    echo $OUT
  fi
fi

