#!/bin/bash
#
# Example post_extract script, committing any changes to a local bzr branch
#

die() {
  echo $*
  exit 1
}

DIR=$1 || exit 1
cd $DIR || exit 2

BZR=/usr/bin/bzr
test -x $BZR || die "Cannot find bzr executable"

# Init a local bzr branch (if required)
test -d .bzr || $BZR init . || die "bzr init failed"

# Commit any changes found
CHANGES=$($BZR status --short)
if [ -n "$CHANGES" ]; then
  NOW=$(date '+%Y-%m-%d %H:%M:%S')
  $BZR add . 2>/dev/null | grep -v Added
  if [ $? -gt 0 ]; then
    die "bzr add failed"
  fi
  $BZR commit --strict -m "Changes to $NOW" | grep -v Committed
  if [ $? -gt 0 ]; then
    die "bzr commit failed"
  fi
fi

