#!/bin/bash
#
# Example post_extract script, committing any changes to a global git branch
#

die() {
  echo $*
  exit 99
}

ROOT=$1 || exit 1
HOST=$2 || exit 2
#FILE=$3 || exit 3

test -n "$ROOT" -a -n "$HOST" || die "usage: $(basename $0) <extract_root> <host>"

test -z "$GIT" && GIT=/usr/bin/git
test -x $GIT || die "Cannot find git executable"

cd $ROOT || die "Cannot cd to '$ROOT'"
test -d .git || $GIT init || die "git init failed"

DIR="$ROOT/$HOST"
cd $DIR || die "Cannot cd to '$DIR'"

$GIT add . && \
$GIT commit -m "Changes to '$(basename $PWD)' to $(date '+%Y-%m-%d %H:%M:%S')." .

