#!/bin/bash
#
# Post_extract script, packing extracted files into a date-stamped tarball
#

ROOT=$1
HOST=$2
FILE=$3
CONFIG=$4

test -f $CONFIG || die "Missing config file $CONFIG"
. $CONFIG

test -n "$ROOT" -a -n "$HOST" || die "usage: $(basename $0) <extract_root> <host>"

DIR="$ROOT/$HOST"
cd $DIR || exit 99

# Create the tarball
tar -zcf $HOST-$(date +%Y%m%d).tar.gz --exclude "$HOST*tar.gz" --remove-files *

# Tar won't remove directories, apparently - so do that explicitly
find . -xdev -depth -type d -regex '^\./.+' -exec rmdir {} \;

