#!/bin/bash
#
# Post_extract script, doing a touch(1) on:
# - the $HOST directory, if called as a post_extract_host script, or:
# - the $ROOT directory, if called as a post_extract_teardown script.
#

die() {
  echo $*
  exit 99
}

ROOT=$1
CONFIG=$2
HOST=$3
FILE=$4

test -n "$ROOT" || die "usage: $(basename $0) <extract_root> [<host>]"

if [ -n "$HOST" ]; then
  DIR="$ROOT/$HOST"
  test -d $DIR || die "Invalid host directory '$DIR'"
else
  DIR=$ROOT
  test -d $DIR || die "Invalid root directory '$DIR'"
fi

touch $DIR || die "Touch on directory '$DIR' failed"

