#!/bin/bash
#
# Example pre_extract script - remove all existing files from a branch
#

die() {
  echo $*
  exit 99
}

ROOT=$1 || exit 1
HOST=$2 || exit 2
FILE=$3 || exit 3

DIR="$ROOT/$HOST"
cd $DIR || die "Cannot cd to '$DIR'"

# Sanity check
/bin/echo $DIR | /bin/grep --quiet extract || die "Bad directory $DIR - does not match 'extract'"

# Do the delete
/bin/rm -rf *

