#!/bin/bash
#
# Example pre_extract_host script (does nothing, example only).
#

die() {
  echo $*
  exit 99
}

ROOT=$1
HOST=$2
FILE=$3

test -n "$ROOT" -a -n "$HOST" || die "usage: $(basename $0) <extract_root> <host> [<file>]"

DIR="$ROOT/$HOST"
cd $DIR || die "Cannot cd to '$DIR'"

# Do something here

